# Generated by Django 4.2.8 on 2023-12-19 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='email', max_length=254, null=True)),
                ('country', models.CharField(help_text='страна', max_length=25)),
                ('city', models.CharField(help_text='город', max_length=25)),
                ('street', models.CharField(help_text='улица', max_length=50)),
                ('house_number', models.PositiveIntegerField(help_text='номер дома', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название продукта', max_length=100)),
                ('model', models.CharField(help_text='модель', max_length=50)),
                ('release_date', models.DateField(help_text='дата выхода на рынок', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название поставщика', max_length=100)),
                ('debt', models.DecimalField(decimal_places=2, default=0, help_text='задолженность перед поставщиком', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='дата и время создания')),
                ('contacts', models.ManyToManyField(help_text='контакты', to='suppliers.contacts')),
                ('products', models.ManyToManyField(help_text='продукты', to='suppliers.products')),
                ('provisioner', models.ForeignKey(help_text='поставщик', null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
