# Generated by Django 4.2.8 on 2023-12-20 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contacts',
            field=models.ManyToManyField(blank=True, help_text='контакты', to='suppliers.contacts'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='продукты', to='suppliers.products'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='provisioner',
            field=models.ForeignKey(blank=True, help_text='поставщик', null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier'),
        ),
    ]
