# Generated by Django 4.2.8 on 2023-12-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_contacts_alter_supplier_products_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-created_at'], 'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, help_text='email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='house_number',
            field=models.PositiveIntegerField(blank=True, help_text='номер дома', null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='release_date',
            field=models.DateField(blank=True, help_text='дата выхода на рынок', null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contacts',
            field=models.ManyToManyField(blank=True, help_text='контакты', null=True, to='suppliers.contacts'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='продукты', null=True, to='suppliers.products'),
        ),
    ]
