# Generated by Django 4.2.8 on 2024-01-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_contacts_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='enterprise_type',
            field=models.CharField(choices=[('factory', 'завод'), ('retail', 'розничная сеть'), ('self-employed', 'индивидуальный предприниматель')], default='self-employed', help_text='тип предприятия', max_length=13),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contacts',
            field=models.ManyToManyField(blank=True, help_text='контакты', to='suppliers.contacts'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='продукты', to='suppliers.products'),
        ),
    ]
